global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
    # Kafka exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9091']

    # Metrics exposed my moderators
  - job_name: 'moderator_metrics'
    static_configs:
      - targets: ['localhost:9009']

    # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
