version: '3.8'
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda-broker
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:19092
      - --set redpanda.enable_idempotence=true
      - --set redpanda.enable_transactions=true
    ports:
      - "19092:9092"  # OUTSIDE listener
      - "29092:29092"  # PLAINTEXT listener
    environment:
      - REDPANDA_RPC_SERVER_LISTEN_ADDR=0.0.0.0
      - REDPANDA_KAFKA_ADDRESS=0.0.0.0:9092
      - REDPANDA_BOOTSTRAP_SERVERS=192.168.88.169:9092  # Your Kafka broker's PLAINTEXT address
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - redpanda-network
  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "7070:8080"
    environment:
      - REDPANDA_BROKERS=192.168.88.169:9092  # Your Kafka broker's PLAINTEXT address
      - REDPANDA_BROKER_CONNECTION_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_BROKERS=192.168.88.169:9092  # Your Kafka broker's PLAINTEXT address
    networks:
      - redpanda-network
volumes:
  redpanda-data:
    driver: local
networks:
  redpanda-network:
    driver: bridge
